### ISSUE TITLE
link is not working

### ISSUE THREAD

**Issue by azeemayaseen** [Outsiders17711/streamlit-Mediapipe-WebApp#1]
Hi, I was trying to access the Streamlip-Mediapipe web app, but it's not working. Is it at the moment or has been moved to some other page? Thanks

**Comment by Outsiders17711** [comment]
Hello,

My apologies for the late response. I somehow missed this issue.

The app was down due to an outdated dependency conflict between Mediapipe and Streamlit. I have fixed the issue and restarted the app. You can check it out [here](https://share.streamlit.io/outsiders17711/streamlit-mediapipe-webapp/main/streamlitMediapipeOnline.py), if you still need to.

Cheers.
